#Arron Birhanu G01315277
#CS 262, Lab section 214
#Project 2

CC = gcc
CFLAGS = -g -Wall -std=c89 -pedantic-errors
TARGET = p2_abirhan2_214


$(TARGET): $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS)

clean:
	rm $(TARGET)
